contact_links:
  - name: Are you looking for documentation on REPO_NAME?
    url: https://USERNAME.github.io/REPO_NAME
    about: Please see the documentation for REPO_NAME on its GitHub Pages page.
  - name: Do want to discuss REPO_NAME with the community?
    url: https://github.com/USERNAME/REPO_NAME/discussions
    about: Please see the discussions page for REPO_NAME.
blank_issues_enabled: true
